# Generated by Django 2.2.6 on 2020-05-01 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('current', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high', models.DecimalField(decimal_places=3, max_digits=8)),
                ('low', models.DecimalField(decimal_places=3, max_digits=8)),
                ('trend', models.CharField(default='NEUTRAL', max_length=10)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('quote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketgurukulapp.Quote')),
                ('recommendation', models.CharField(default='NEUTRAL', max_length=4)),
            ],
            bases=('marketgurukulapp.quote',),
        ),
    ]
