# Generated by Django 2.2.6 on 2020-05-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgurukulapp', '0002_quote_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='average_volume',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
