# Generated by Django 2.2.6 on 2020-05-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgurukulapp', '0003_quote_average_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='average_volume',
            field=models.IntegerField(default=0.0),
        ),
    ]
