# Generated by Django 2.2.6 on 2020-05-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketgurukulapp', '0004_auto_20200501_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='current',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='quote',
            name='high',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='quote',
            name='low',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
